name: Code Format Checks

on:
  pull_request:
    branches:
      - main-wallet-dm

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.14.0
          cache: "npm"
      - name: Run Code Format Check
        run: |
          npm install 
          npm run fmt:check
